In [1]:
import pandas as pd
import numpy as np
import os

In [32]:
import pandas as pd
import os

base_path = r"251128\251128"
path = ["1/17705.tsv", "1/27289.tsv", "1/26084.tsv", "1/7517.tsv", "1/26511.tsv", "1/2849.tsv", "1/7260.tsv", "1/27763.tsv", "1/26697.tsv", "1/27231.tsv" ]
dfs = []
for p in path:
    if 'SpectrumID' not in df.columns:
        df['SpectrumID'] = os.path.basename(file_path)
    file_path = os.path.join(base_path, p)
    df = pd.read_csv(file_path, sep=r'\t|,|\s+', engine='python')
    dfs.append(df)


df = pd.concat(dfs, ignore_index=True)

df.head()

,PrecursorCharge,ModifiedPeptide,FragmentLossType,FragmentNumber,FragmentType,FragmentCharge,RelativeIntensity,SpectrumID
0,2,_AEEDEILNRS(UniMod:21)PR_,noloss,1,y,1,0.085714,17705.tsv
1,2,_AEEDEILNRS(UniMod:21)PR_,noloss,2,y,1,1.000000,17705.tsv
2,2,_AEEDEILNRS(UniMod:21)PR_,noloss,3,y,1,0.028571,17705.tsv
3,2,_AEEDEILNRS(UniMod:21)PR_,noloss,4,y,1,0.014286,17705.tsv
4,2,_AEEDEILNRS(UniMod:21)PR_,noloss,5,y,1,0.057143,17705.tsv

In [26]:
df.shape

(625, 7)

In [33]:

df.head(100)

,PrecursorCharge,ModifiedPeptide,FragmentLossType,FragmentNumber,FragmentType,FragmentCharge,RelativeIntensity,SpectrumID
0,2,_AEEDEILNRS(UniMod:21)PR_,noloss,1,y,1,0.085714,17705.tsv
1,2,_AEEDEILNRS(UniMod:21)PR_,noloss,2,y,1,1.000000,17705.tsv
2,2,_AEEDEILNRS(UniMod:21)PR_,noloss,3,y,1,0.028571,17705.tsv
3,2,_AEEDEILNRS(UniMod:21)PR_,noloss,4,y,1,0.014286,17705.tsv
4,2,_AEEDEILNRS(UniMod:21)PR_,noloss,5,y,1,0.057143,17705.tsv
...,...,...,...,...,...,...,...,...
95,2,_AEEDEILNRS(UniMod:21)PR_,1(+H2+O),8,y,1,0.030000,27289.tsv
96,2,_AEEDEILNRS(UniMod:21)PR_,1(+H2+O),10,y,1,0.040000,27289.tsv
97,2,_AEEDEILNRS(UniMod:21)PR_,1(+H2+O),11,y,1,0.015000,27289.tsv
98,2,_AEEDEILNRS(UniMod:21)PR_,1(+H3+N),3,y,1,0.003000,27289.tsv
99,2,_AEEDEILNRS(UniMod:21)PR_,1(+H3+N),4,y,1,0.010000,27289.tsv

In [34]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)

Shape: (625, 8)

Columns:
Index(['PrecursorCharge', 'ModifiedPeptide', 'FragmentLossType',
       'FragmentNumber', 'FragmentType', 'FragmentCharge', 'RelativeIntensity',
       'SpectrumID'],
      dtype='object')

In [35]:
max_intensity = df.groupby('SpectrumID')['RelativeIntensity'].max()
max_intensity

SpectrumID
17705.tsv    1.0
26084.tsv    1.0
26511.tsv    1.0
26697.tsv    1.0
27289.tsv    1.0
27763.tsv    1.0
2849.tsv     1.0
7260.tsv     1.0
7517.tsv     1.0
Name: RelativeIntensity, dtype: float64

In [36]:
df['frag_key'] = (
    df['FragmentType'].astype(str) + "_" +
    df['FragmentNumber'].astype(str) + "_" +
    df['FragmentLossType'].astype(str) + "_ch" +
    df['FragmentCharge'].astype(str)
)

df[['FragmentType','FragmentNumber','FragmentLossType','FragmentCharge','frag_key']].head(10)

,FragmentType,FragmentNumber,FragmentLossType,FragmentCharge,frag_key
0,y,1,noloss,1,y_1_noloss_ch1
1,y,2,noloss,1,y_2_noloss_ch1
2,y,3,noloss,1,y_3_noloss_ch1
3,y,4,noloss,1,y_4_noloss_ch1
4,y,5,noloss,1,y_5_noloss_ch1
5,y,6,noloss,1,y_6_noloss_ch1
6,y,7,noloss,1,y_7_noloss_ch1
7,y,8,noloss,1,y_8_noloss_ch1
8,y,9,noloss,1,y_9_noloss_ch1
9,y,10,noloss,1,y_10_noloss_ch1

In [37]:
duplicate_check = (
    df.groupby(['SpectrumID','frag_key'])
      .size()
      .reset_index(name='count')
)

duplicate_check[duplicate_check['count'] > 1]

    SpectrumID           frag_key  count
0    17705.tsv  b_10_1(+H2+O)_ch1      2
1    17705.tsv  b_10_1(+H3+N)_ch1      2
21   17705.tsv  y_10_1(+H3+N)_ch1      2
24   17705.tsv  y_11_1(+H2+O)_ch1      2
38   17705.tsv   y_5_1(+H3+N)_ch1      2
..         ...                ...    ...
453   7517.tsv  y_11_1(+H2+O)_ch1      2
467   7517.tsv   y_5_1(+H3+N)_ch1      2
470   7517.tsv   y_6_1(+H3+N)_ch1      2
473   7517.tsv   y_7_1(+H3+N)_ch1      2
476   7517.tsv   y_8_1(+H2+O)_ch1      2

[80 rows x 3 columns]

In [38]:
agg = (
    df.groupby(['SpectrumID', 'frag_key'])['RelativeIntensity']
      .mean()
      .reset_index()
)

agg.head(10)

  SpectrumID           frag_key  RelativeIntensity
0  17705.tsv  b_10_1(+H2+O)_ch1           0.010000
1  17705.tsv  b_10_1(+H3+N)_ch1           0.019286
2  17705.tsv     b_10_H3PO4_ch1           1.000000
3  17705.tsv    b_10_noloss_ch1           0.142857
4  17705.tsv     b_11_H3PO4_ch1           0.028571
5  17705.tsv     b_2_noloss_ch1           0.085714
6  17705.tsv   b_3_1(+H2+O)_ch1           0.004286
7  17705.tsv     b_3_noloss_ch1           0.014286
8  17705.tsv   b_4_1(+H2+O)_ch1           0.014286
9  17705.tsv     b_4_noloss_ch1           0.042857

In [39]:
check_after = (
    agg.groupby(['SpectrumID','frag_key'])
       .size()
       .reset_index(name='count')
)

check_after[check_after['count'] > 1]

Empty DataFrame
Columns: [SpectrumID, frag_key, count]
Index: []

In [40]:
max_per_spec = agg.groupby('SpectrumID')['RelativeIntensity'].max()

max_per_spec

SpectrumID
17705.tsv    1.0
26084.tsv    1.0
26511.tsv    1.0
26697.tsv    1.0
27289.tsv    1.0
27763.tsv    1.0
2849.tsv     1.0
7260.tsv     1.0
7517.tsv     1.0
Name: RelativeIntensity, dtype: float64

In [41]:
agg['RelNorm'] = agg['RelativeIntensity']
agg.head()

  SpectrumID           frag_key  RelativeIntensity   RelNorm
0  17705.tsv  b_10_1(+H2+O)_ch1           0.010000  0.010000
1  17705.tsv  b_10_1(+H3+N)_ch1           0.019286  0.019286
2  17705.tsv     b_10_H3PO4_ch1           1.000000  1.000000
3  17705.tsv    b_10_noloss_ch1           0.142857  0.142857
4  17705.tsv     b_11_H3PO4_ch1           0.028571  0.028571

In [43]:
mat = agg.pivot(
    index='SpectrumID',
    columns='frag_key',
    values='RelNorm'
).fillna(0)

mat.head(10)

frag_key,b_10_1(+H2+O)_ch1,b_10_1(+H3+N)_ch1,b_10_H3PO4_ch1,b_10_noloss_ch1,b_11_H3PO4_ch1,b_11_noloss_ch1,b_2_noloss_ch1,b_3_1(+H2+O)_ch1,b_3_noloss_ch1,b_4_1(+H2+O)_ch1,...,y_7_1(+H3+N)_ch1,y_7_H3PO4_ch1,y_7_noloss_ch1,y_8_1(+H2+O)_ch1,y_8_1(+H3+N)_ch1,y_8_H3PO4_ch1,y_8_noloss_ch1,y_9_1(+H3+N)_ch1,y_9_H3PO4_ch1,y_9_noloss_ch1
SpectrumID,,,,,,,,,,,,,,,,,,,,,
17705.tsv,0.010000,0.019286,1.00,0.142857,0.028571,0.0000,0.085714,0.004286,0.014286,0.014286,...,0.018571,0.071429,0.057143,0.035714,0.008571,0.285714,0.114286,0.016429,0.100000,0.057143
26084.tsv,0.041667,0.000000,1.00,0.166667,0.033333,0.0000,0.083333,0.003333,0.016667,0.013333,...,0.013333,0.066667,0.066667,0.033333,0.013333,0.333333,0.100000,0.020000,0.116667,0.066667
26511.tsv,0.012500,0.037500,1.00,0.125000,0.025000,0.0000,0.087500,0.003750,0.025000,0.012500,...,0.016875,0.062500,0.062500,0.031250,0.012500,0.250000,0.112500,0.016250,0.100000,0.062500
26697.tsv,0.017500,0.025000,1.00,0.100000,0.025000,0.0015,0.050000,0.001500,0.015000,0.010000,...,0.015000,0.050000,0.045000,0.025000,0.006750,0.200000,0.100000,0.014250,0.100000,0.050000
27289.tsv,0.015000,0.017500,1.00,0.100000,0.030000,0.0000,0.100000,0.003500,0.025000,0.010000,...,0.015000,0.050000,0.050000,0.035000,0.010000,0.300000,0.100000,0.020000,0.100000,0.045000
27763.tsv,0.013500,0.020000,0.90,0.100000,0.030000,0.0000,0.080000,0.003000,0.020000,0.010000,...,0.014000,0.070000,0.060000,0.030000,0.008500,0.200000,0.090000,0.017000,0.090000,0.060000
2849.tsv,0.020000,0.030000,1.00,0.166667,0.026667,0.0000,0.066667,0.003000,0.020000,0.010000,...,0.018333,0.066667,0.066667,0.031667,0.013333,0.300000,0.133333,0.018333,0.100000,0.066667
7260.tsv,0.010000,0.017500,0.50,0.100000,0.020000,0.0000,0.050000,0.003000,0.015000,0.010000,...,0.012500,0.050000,0.045000,0.025000,0.010000,0.200000,0.050000,0.012250,0.100000,0.045000
7517.tsv,0.013750,0.025000,0.75,0.075000,0.050000,0.0000,0.100000,0.005000,0.022500,0.020000,...,0.016250,0.075000,0.050000,0.026250,0.025000,0.250000,0.075000,0.025000,0.125000,0.050000

In [44]:
print("Matrix shape:", mat.shape)

Matrix shape: (9, 56)

In [46]:
mat.iloc[1]

frag_key
b_10_1(+H2+O)_ch1    0.041667
b_10_1(+H3+N)_ch1    0.000000
b_10_H3PO4_ch1       1.000000
b_10_noloss_ch1      0.166667
b_11_H3PO4_ch1       0.033333
b_11_noloss_ch1      0.000000
b_2_noloss_ch1       0.083333
b_3_1(+H2+O)_ch1     0.003333
b_3_noloss_ch1       0.016667
b_4_1(+H2+O)_ch1     0.013333
b_4_noloss_ch1       0.033333
b_5_1(+H2+O)_ch1     0.016667
b_5_noloss_ch1       0.083333
b_6_1(+H2+O)_ch1     0.010000
b_6_noloss_ch1       0.050000
b_7_1(+H2+O)_ch1     0.000000
b_7_noloss_ch1       0.016667
b_8_1(+H3+N)_ch1     0.003333
b_8_noloss_ch1       0.005000
b_9_1(+H2+O)_ch1     0.008333
b_9_noloss_ch1       0.066667
y_10_1(+H2+O)_ch1    0.041667
y_10_1(+H3+N)_ch1    0.018333
y_10_H3PO4_ch1       0.166667
y_10_noloss_ch1      0.083333
y_11_1(+H2+O)_ch1    0.015000
y_11_H3PO4_ch1       0.033333
y_11_noloss_ch1      0.015000
y_1_1(+H3+N)_ch1     0.006667
y_1_noloss_ch1       0.083333
y_2_1(+H3+N)_ch1     0.016667
y_2_noloss_ch1       1.000000
y_3_1(+H2+O)_ch1     0.016667
y_3_1(+H3+N)_ch1     0.001667
y_3_H3PO4_ch1        0.016667
y_3_noloss_ch1       0.033333
y_4_1(+H3+N)_ch1     0.011667
y_4_H3PO4_ch1        0.011667
y_4_noloss_ch1       0.016667
y_5_1(+H3+N)_ch1     0.025000
y_5_H3PO4_ch1        0.033333
y_5_noloss_ch1       0.083333
y_6_1(+H3+N)_ch1     0.033333
y_6_H3PO4_ch1        0.050000
y_6_noloss_ch1       0.100000
y_7_1(+H2+O)_ch1     0.000000
y_7_1(+H3+N)_ch1     0.013333
y_7_H3PO4_ch1        0.066667
y_7_noloss_ch1       0.066667
y_8_1(+H2+O)_ch1     0.033333
y_8_1(+H3+N)_ch1     0.013333
y_8_H3PO4_ch1        0.333333
y_8_noloss_ch1       0.100000
y_9_1(+H3+N)_ch1     0.020000
y_9_H3PO4_ch1        0.116667
y_9_noloss_ch1       0.066667
Name: 26084.tsv, dtype: float64

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

sims = cosine_similarity(mat.values)

sim_df = pd.DataFrame(
    sims,
    index=mat.index,
    columns=mat.index
)

sim_df

SpectrumID,17705.tsv,26084.tsv,26511.tsv,26697.tsv,27289.tsv,27763.tsv,2849.tsv,7260.tsv,7517.tsv
SpectrumID,,,,,,,,,
17705.tsv,1.000000,0.998422,0.996586,0.996227,0.998102,0.995723,0.998396,0.951178,0.984834
26084.tsv,0.998422,1.000000,0.995468,0.992545,0.997332,0.993353,0.998258,0.950237,0.984816
26511.tsv,0.996586,0.995468,1.000000,0.994793,0.998105,0.997546,0.997883,0.951097,0.988202
26697.tsv,0.996227,0.992545,0.994793,1.000000,0.994286,0.996211,0.993769,0.950237,0.981841
27289.tsv,0.998102,0.997332,0.998105,0.994286,1.000000,0.996273,0.997738,0.950722,0.987970
27763.tsv,0.995723,0.993353,0.997546,0.996211,0.996273,1.000000,0.995184,0.965266,0.992375
2849.tsv,0.998396,0.998258,0.997883,0.993769,0.997738,0.995184,1.000000,0.950495,0.985489
7260.tsv,0.951178,0.950237,0.951097,0.950237,0.950722,0.965266,0.950495,1.000000,0.980711
7517.tsv,0.984834,0.984816,0.988202,0.981841,0.987970,0.992375,0.985489,0.980711,1.000000

In [48]:
# Bỏ đường chéo
mask = ~np.eye(sim_df.shape[0], dtype=bool)
min_similarity = sim_df.where(mask).min().min()

min_similarity

0.9502370228528841