In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
import os
import re
import torch
import torch.nn as nn
import math
from torch.utils.data import Dataset, DataLoader

In [2]:
index_df = pd.read_csv(
    r"D:/DACN/tf-test/tf_modification_ms2/data/_index.tsv",
    header=None
)

print(index_df.head())

             0
0  1/17705.tsv
1  1/27289.tsv
2  1/26084.tsv
3   1/7517.tsv
4  1/26511.tsv

In [3]:
base_dir = r"D:/DACN/tf-test/tf_modification_ms2/data/251128"

dfs = []

for i, rel_path in enumerate(index_df[0]):
    full_path = os.path.join(base_dir, rel_path)
    
    temp = pd.read_csv(full_path, sep="\t")
    temp["psm_id"] = f"psm_{i}"  
    
    dfs.append(temp)

In [4]:
df = pd.concat(dfs, ignore_index=True)

print(df.head())
print(f"Total rows: {len(df)}")

   PrecursorCharge            ModifiedPeptide FragmentLossType  \
0                2  _AEEDEILNRS(UniMod:21)PR_           noloss
1                2  _AEEDEILNRS(UniMod:21)PR_           noloss
2                2  _AEEDEILNRS(UniMod:21)PR_           noloss
3                2  _AEEDEILNRS(UniMod:21)PR_           noloss
4                2  _AEEDEILNRS(UniMod:21)PR_           noloss

   FragmentNumber FragmentType FragmentCharge  RelativeIntensity psm_id
0               1            y              1           0.085714  psm_0
1               2            y              1           1.000000  psm_0
2               3            y              1           0.028571  psm_0
3               4            y              1           0.014286  psm_0
4               5            y              1           0.057143  psm_0
Total rows: 35702

In [27]:
frag_types = [
        "b_z1", "b_z2", "y_z1", "y_z2",
        "b_modloss_z1", "b_modloss_z2",
        "y_modloss_z1", "y_modloss_z2"
    ]

In [28]:
import pandas as pd
import numpy as np
import re

def fast_preprocess(df):

    df['clean_seq'] = df['ModifiedPeptide'].str.strip('_').str.replace(r'\(.*?\)', '', regex=True)
    df['L'] = df['clean_seq'].str.len()
    df['charge_num'] = df['FragmentCharge'].astype(str).str.extract('(\d+)').astype(int)
    df['loss_clean'] = df['FragmentLossType'].apply(lambda x: '' if x == 'noloss' else '_modloss')
    df['target_col'] = df['FragmentType'] + df['loss_clean'] + '_z' + df['charge_num'].astype(str)
    
    
    pivot_df = df.pivot_table(
        index=['psm_id', 'FragmentNumber'], 
        columns='target_col', 
        values='RelativeIntensity', 
        aggfunc='max' 
    )

    
    pivot_df = pivot_df.reindex(columns=frag_types, fill_value=0.0).fillna(0)

    
    results = {}
    for psm_id, group in pivot_df.groupby(level=0):
       
        L = df[df['psm_id'] == psm_id]['L'].iloc[0]
        
     
        actual_matrix = group.loc[(psm_id, 1):(psm_id, L-1)]
        
       
        if len(actual_matrix) < (L - 1):
            actual_matrix = actual_matrix.reindex(
                pd.MultiIndex.from_product([[psm_id], range(1, L)]), 
                fill_value=0.0
            )
            
        results[psm_id] = actual_matrix.values

    return results


results = fast_preprocess(df)

# Kiểm tra thử psm_0
if 'psm_0' in results:
    print(f"--- Kết quả cho psm_0 ---")
    print(f"Shape của ma trận: {results['psm_0'].shape}")

--- Kết quả cho psm_0 ---
Shape của ma trận: (11, 8)

In [49]:
sample_id = 'psm_170'
group = df[df['psm_id'] == sample_id]
L = group['L'].iloc[29]

debug_matrix = pd.DataFrame(0.0, index=range(1, L), columns=frag_types)

for _, row in group.iterrows():
    target = row['target_col']
    frag = int(row['FragmentNumber'])
    val = row['RelativeIntensity']
    
    if target in frag_types:
        debug_matrix.at[frag, target] = max(
            debug_matrix.at[frag, target], val
        )

print(f"--- Kiểm tra Peptide: {group['ModifiedPeptide'].iloc[0]} (L={L}) ---")
print(debug_matrix)

--- Kiểm tra Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_ (L=24) ---
     b_z1   b_z2  y_z1   y_z2  b_modloss_z1  b_modloss_z2  y_modloss_z1  \
1   0.000  0.000  0.00  0.000         0.000           0.0         0.000
2   0.000  0.000  0.02  0.000         0.000           0.0         0.020
3   0.200  0.000  0.12  0.000         0.140           0.0         0.000
4   0.060  0.000  0.06  0.000         0.140           0.0         0.012
5   0.040  0.000  0.06  0.000         0.040           0.0         0.000
6   0.020  0.000  0.20  0.000         0.008           0.0         0.008
7   0.000  0.000  0.40  0.000         0.080           0.0         0.040
8   0.000  0.000  0.08  0.000         0.000           0.0         0.000
9   0.000  0.000  0.20  0.000         0.020           0.0         0.000
10  0.080  0.000  0.20  0.000         0.060           0.0         0.012
11  0.000  0.000  0.10  0.000         0.000           0.0         0.000
12  0.000  0.000  0.04  0.000         0.000           0.0         0.000
13  0.020  0.000  0.02  0.012         0.016           0.0         0.000
14  0.000  0.008  1.00  0.000         0.010           0.0         0.100
15  0.060  0.000  0.10  0.000         0.010           0.0         0.000
16  0.000  0.014  0.02  0.000         0.000           0.0         0.000
17  0.000  0.016  0.60  0.000         0.000           0.0         0.060
18  0.014  0.000  0.08  0.000         0.020           0.0         0.200
19  0.014  0.000  0.20  0.000         0.000           0.0         0.400
20  0.000  0.000  0.60  0.000         0.000           0.0         0.600
21  0.014  0.000  0.40  0.000         0.008           0.0         0.160
22  0.000  0.000  0.80  0.000         0.000           0.0         0.600
23  0.012  0.000  0.00  0.000         0.000           0.0         0.000

    y_modloss_z2
1            0.0
2            0.0
3            0.0
4            0.0
5            0.0
6            0.0
7            0.0
8            0.0
9            0.0
10           0.0
11           0.0
12           0.0
13           0.0
14           0.0
15           0.0
16           0.0
17           0.0
18           0.0
19           0.0
20           0.0
21           0.0
22           0.0
23           0.0

In [48]:
# Khởi tạo dictionary để lưu kết quả mỗi PSM
psm_nonzero_z2 = {}

# Lặp qua từng PSM
for sample_id, group in df.groupby('psm_id'):
    L = group['L'].iloc[0]
    
    # Khởi tạo matrix fragment
    debug_matrix = pd.DataFrame(0.0, index=range(1, L), columns=frag_types)
    
    # Fill matrix
    for _, row in group.iterrows():
        target = row['target_col']
        frag = int(row['FragmentNumber'])
        val = row['RelativeIntensity']
        
        if target in frag_types:
            debug_matrix.at[frag, target] = max(debug_matrix.at[frag, target], val)
    
    # Chỉ giữ fragment b/z 2 > 0
    b_y_z2_cols = ['b_z2', 'y_z2', 'b_modloss_z2', 'y_modloss_z2']
    nonzero_fragments = debug_matrix[b_y_z2_cols][debug_matrix[b_y_z2_cols] > 0].dropna(how='all')
    
    # Nếu có ít nhất 1 fragment >0, lưu lại
    if not nonzero_fragments.empty:
        psm_nonzero_z2[sample_id] = {
            'peptide': group['ModifiedPeptide'].iloc[0],
            'matrix': nonzero_fragments
        }

# --- In ra kết quả ---
for psm_id, info in psm_nonzero_z2.items():
    print(f"PSM ID: {psm_id}, Peptide: {info['peptide']}")
    print(info['matrix'], "\n")

PSM ID: psm_170, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
     b_z2   y_z2  b_modloss_z2  y_modloss_z2
13    NaN  0.012           NaN           NaN
14  0.008    NaN           NaN           NaN
16  0.014    NaN           NaN           NaN
17  0.016    NaN           NaN           NaN

PSM ID: psm_171, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
        b_z2  y_z2  b_modloss_z2  y_modloss_z2
16  0.016667   NaN           NaN           NaN
18       NaN  0.05           NaN           NaN
19  0.010000   NaN           NaN           NaN

PSM ID: psm_172, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
     b_z2  y_z2  b_modloss_z2  y_modloss_z2
13    NaN  0.01           NaN           NaN
16  0.010   NaN           NaN           NaN
19  0.009   NaN           NaN           NaN

PSM ID: psm_173, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
      b_z2  y_z2  b_modloss_z2  y_modloss_z2
13     NaN  0.01           NaN           NaN
16  0.0150   NaN           NaN           NaN
17  0.0125   NaN           NaN           NaN
19  0.0100   NaN           NaN           NaN
21  0.0125   NaN           NaN           NaN

PSM ID: psm_174, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
12       NaN  0.011638           NaN           NaN
16       NaN  0.016706           NaN           NaN
19  0.004770       NaN           NaN           NaN
21  0.006552       NaN           NaN           NaN

PSM ID: psm_175, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
12       NaN  0.011638           NaN           NaN
16       NaN  0.016706           NaN           NaN
19  0.004770       NaN           NaN           NaN
21  0.006552       NaN           NaN           NaN

PSM ID: psm_176, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
      b_z2  y_z2  b_modloss_z2  y_modloss_z2
18  0.0075   NaN           NaN           NaN

PSM ID: psm_177, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
    b_z2  y_z2  b_modloss_z2  y_modloss_z2
16  0.01   NaN           NaN           NaN

PSM ID: psm_178, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
16  0.014286       NaN           NaN           NaN
17  0.014286       NaN           NaN           NaN
22  0.005714       NaN           NaN           NaN
23       NaN  0.002857           NaN           NaN

PSM ID: psm_179, Peptide: _AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
12       NaN  0.016667           NaN           NaN
16  0.020000       NaN           NaN           NaN
17  0.010000       NaN           NaN           NaN
22  0.006667       NaN           NaN           NaN

PSM ID: psm_190, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
     b_z2  y_z2  b_modloss_z2  y_modloss_z2
11  0.004   NaN           NaN           NaN
27  0.009  0.02           NaN           NaN

PSM ID: psm_191, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
     b_z2  y_z2  b_modloss_z2  y_modloss_z2
11  0.006   NaN           NaN           NaN
27    NaN  0.03           NaN           NaN
29  0.050   NaN           NaN           NaN

PSM ID: psm_192, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
11  0.003333       NaN           NaN           NaN
26       NaN  0.033333           NaN           NaN
27  0.010000       NaN           NaN           NaN

PSM ID: psm_193, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
11  0.006667       NaN           NaN           NaN
27       NaN  0.016667           NaN           NaN

PSM ID: psm_194, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
11  0.003333       NaN           NaN           NaN
27       NaN  0.016667           NaN           NaN

PSM ID: psm_195, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
20   NaN  0.014286           NaN           NaN
27   NaN  0.014286           NaN           NaN

PSM ID: psm_196, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
     b_z2  y_z2  b_modloss_z2  y_modloss_z2
11  0.004   NaN           NaN           NaN
27  0.010  0.02           NaN           NaN

PSM ID: psm_197, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
11  0.004286       NaN           NaN           NaN
26       NaN  0.042857           NaN           NaN
27       NaN  0.014286           NaN           NaN

PSM ID: psm_198, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
      b_z2   y_z2  b_modloss_z2  y_modloss_z2
11  0.0050    NaN           NaN           NaN
27  0.0125  0.015           NaN           NaN
29  0.0175    NaN           NaN           NaN

PSM ID: psm_199, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_
     b_z2  y_z2  b_modloss_z2  y_modloss_z2
11  0.007   NaN           NaN           NaN
27  0.010  0.02           NaN           NaN

PSM ID: psm_200, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
     b_z2  y_z2  b_modloss_z2  y_modloss_z2
23    NaN  0.04           NaN           NaN
24    NaN  0.05           NaN           NaN
27  0.005   NaN           NaN           NaN
29  0.025   NaN           NaN           NaN
37    NaN  0.05           NaN           NaN

PSM ID: psm_201, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
22       NaN  0.028571           NaN           NaN
24       NaN  0.057143           NaN           NaN
29  0.042857  0.028571           NaN           NaN
30       NaN  0.028571           NaN           NaN
32       NaN  0.057143           NaN           NaN
37       NaN  0.042857           NaN           NaN

PSM ID: psm_202, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
    b_z2  y_z2  b_modloss_z2  y_modloss_z2
23   NaN  0.05           NaN           NaN
27  0.02   NaN           NaN           NaN
29  0.03   NaN           NaN           NaN
37   NaN  0.10           NaN           NaN

PSM ID: psm_203, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
     b_z2   y_z2  b_modloss_z2  y_modloss_z2
17    NaN  0.060           NaN           NaN
22    NaN  0.040           NaN           NaN
27  0.006    NaN           NaN           NaN
29  0.018    NaN           NaN           NaN
36    NaN  0.018           NaN           NaN
37    NaN  0.080           NaN           NaN

PSM ID: psm_204, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
23       NaN  0.066667           NaN           NaN
30  0.033333       NaN           NaN           NaN
33  0.022222       NaN           NaN           NaN
37       NaN  0.066667           NaN           NaN

PSM ID: psm_205, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
22       NaN  0.023333           NaN           NaN
23       NaN  0.023333           NaN           NaN
29  0.026667       NaN           NaN           NaN
37       NaN  0.066667           NaN           NaN

PSM ID: psm_206, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
    b_z2   y_z2  b_modloss_z2  y_modloss_z2
13   NaN  0.008           NaN           NaN
22   NaN  0.020           NaN           NaN
23   NaN  0.060           NaN           NaN
27  0.01    NaN           NaN           NaN
29  0.04    NaN           NaN           NaN
37   NaN  0.040           NaN           NaN

PSM ID: psm_207, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
11  0.007143       NaN           NaN           NaN
22       NaN  0.042857           NaN           NaN
24       NaN  0.100000           NaN           NaN
27  0.004286       NaN           NaN           NaN
29  0.011429       NaN           NaN           NaN
37       NaN  0.057143           NaN           NaN

PSM ID: psm_208, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
     b_z2   y_z2  b_modloss_z2  y_modloss_z2
22  0.010  0.015           NaN           NaN
27  0.010    NaN           NaN           NaN
29  0.025    NaN           NaN           NaN
37    NaN  0.040           NaN           NaN

PSM ID: psm_209, Peptide: _C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_
    b_z2  y_z2  b_modloss_z2  y_modloss_z2
23   NaN  0.04           NaN           NaN
24   NaN  0.09           NaN           NaN
37   NaN  0.20           NaN           NaN

PSM ID: psm_210, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
19  0.006667       NaN           NaN           NaN
20       NaN  0.100000           NaN           NaN
22  0.010000       NaN           NaN           NaN
24       NaN  0.013333           NaN           NaN

PSM ID: psm_211, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
19  0.011111       NaN           NaN           NaN
20       NaN  0.111111           NaN           NaN
24       NaN  0.011111           NaN           NaN

PSM ID: psm_212, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
     b_z2  y_z2  b_modloss_z2  y_modloss_z2
19  0.010   NaN           NaN           NaN
20    NaN  0.20           NaN           NaN
24  0.010  0.01           NaN           NaN
25  0.006   NaN           NaN           NaN

PSM ID: psm_213, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
    b_z2  y_z2  b_modloss_z2  y_modloss_z2
20   NaN  0.10           NaN           NaN
24  0.01  0.02           NaN           NaN

PSM ID: psm_214, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
     b_z2   y_z2  b_modloss_z2  y_modloss_z2
19  0.005    NaN           NaN           NaN
20    NaN  0.100           NaN           NaN
24    NaN  0.005           NaN           NaN

PSM ID: psm_215, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
     b_z2  y_z2  b_modloss_z2  y_modloss_z2
14  0.006   NaN           NaN           NaN
20    NaN  0.10           NaN           NaN
24    NaN  0.01           NaN           NaN

PSM ID: psm_216, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
     b_z2  y_z2  b_modloss_z2  y_modloss_z2
19  0.010   NaN           NaN           NaN
20    NaN  0.10           NaN           NaN
24  0.005  0.01           NaN           NaN
25  0.002   NaN           NaN           NaN

PSM ID: psm_217, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
    b_z2  y_z2  b_modloss_z2  y_modloss_z2
13   NaN  0.02           NaN           NaN
20   NaN  0.10           NaN           NaN
24   NaN  0.02           NaN           NaN

PSM ID: psm_218, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
20   NaN  0.111111           NaN           NaN
24   NaN  0.011111           NaN           NaN

PSM ID: psm_219, Peptide: _DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
19  0.010000       NaN           NaN           NaN
20       NaN  0.128571           NaN           NaN
24       NaN  0.014286           NaN           NaN
25  0.005714       NaN           NaN           NaN

PSM ID: psm_250, Peptide: _DSELY(UniMod:21)FLGT(UniMod:21)DT(UniMod:21)HKKK_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
14   NaN  0.005943           NaN           NaN

PSM ID: psm_251, Peptide: _DSELY(UniMod:21)FLGT(UniMod:21)DT(UniMod:21)HKKK_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
14   NaN  0.005943           NaN           NaN

PSM ID: psm_252, Peptide: _DSELY(UniMod:21)FLGT(UniMod:21)DT(UniMod:21)HKKK_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
14   NaN  0.005943           NaN           NaN

PSM ID: psm_254, Peptide: _DSELY(UniMod:21)FLGT(UniMod:21)DT(UniMod:21)HKKK_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
14   NaN  0.015478           NaN           NaN

PSM ID: psm_255, Peptide: _DSELY(UniMod:21)FLGT(UniMod:21)DT(UniMod:21)HKKK_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
14   NaN  0.011111           NaN           NaN

PSM ID: psm_258, Peptide: _DSELY(UniMod:21)FLGT(UniMod:21)DT(UniMod:21)HKKK_
        b_z2  y_z2  b_modloss_z2  y_modloss_z2
14  0.005293   NaN           NaN           NaN

PSM ID: psm_259, Peptide: _DSELY(UniMod:21)FLGT(UniMod:21)DT(UniMod:21)HKKK_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
13   NaN  0.187069           NaN           NaN
14   NaN  0.026865           NaN           NaN

PSM ID: psm_260, Peptide: _DTLRT(UniMod:21)PPRER_
   b_z2   y_z2  b_modloss_z2  y_modloss_z2
8   NaN  0.006           NaN           NaN

PSM ID: psm_261, Peptide: _DTLRT(UniMod:21)PPRER_
   b_z2   y_z2  b_modloss_z2  y_modloss_z2
8   NaN  0.004           NaN           NaN

PSM ID: psm_263, Peptide: _DTLRT(UniMod:21)PPRER_
       b_z2  y_z2  b_modloss_z2  y_modloss_z2
9  0.006667   NaN           NaN           NaN

PSM ID: psm_264, Peptide: _DTLRT(UniMod:21)PPRER_
   b_z2   y_z2  b_modloss_z2  y_modloss_z2
6   NaN  0.005           NaN           NaN

PSM ID: psm_265, Peptide: _DTLRT(UniMod:21)PPRER_
       b_z2  y_z2  b_modloss_z2  y_modloss_z2
9  0.004943   NaN           NaN           NaN

PSM ID: psm_268, Peptide: _DTLRT(UniMod:21)PPRER_
    b_z2  y_z2  b_modloss_z2  y_modloss_z2
9  0.007   NaN           NaN           NaN

PSM ID: psm_270, Peptide: _DWEDDS(UniMod:21)DEDMSNFDR_
    b_z2     y_z2  b_modloss_z2  y_modloss_z2
13   NaN  0.01677           NaN           NaN

PSM ID: psm_271, Peptide: _DWEDDS(UniMod:21)DEDMSNFDR_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
13   NaN  0.012819           NaN           NaN

PSM ID: psm_272, Peptide: _DWEDDS(UniMod:21)DEDMSNFDR_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
13   NaN  0.018071           NaN           NaN

PSM ID: psm_273, Peptide: _DWEDDS(UniMod:21)DEDMSNFDR_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
13   NaN  0.015514           NaN           NaN

PSM ID: psm_274, Peptide: _DWEDDS(UniMod:21)DEDMSNFDR_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
11   NaN  0.010876           NaN           NaN

PSM ID: psm_278, Peptide: _DWEDDS(UniMod:21)DEDMSNFDR_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
11   NaN  0.012074           NaN           NaN
13   NaN  0.029265           NaN           NaN

PSM ID: psm_279, Peptide: _DWEDDS(UniMod:21)DEDMSNFDR_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
13   NaN  0.023168           NaN           NaN

PSM ID: psm_30, Peptide: _AHT(UniMod:21)PTPGIYMGRPTHSGGGGGGGGGGGGGGGGR_
      b_z2    y_z2  b_modloss_z2  y_modloss_z2
6      NaN  0.0150           NaN           NaN
8      NaN  0.0100           NaN           NaN
9      NaN  0.0100           NaN           NaN
10     NaN  0.0125           NaN           NaN
12     NaN  0.0125           NaN           NaN
13     NaN  0.0075           NaN           NaN
14     NaN  0.0050           NaN           NaN
15     NaN  0.0050           NaN           NaN
16  0.0050  0.0050           NaN           NaN
17     NaN  0.0050           NaN           NaN
19     NaN  0.0100           NaN           NaN
21  0.0025  0.0175           NaN           NaN
22  0.0050     NaN           NaN           NaN
23  0.0050     NaN           NaN           NaN
24  0.0050     NaN           NaN           NaN
25  0.0050     NaN           NaN           NaN

PSM ID: psm_31, Peptide: _AHT(UniMod:21)PTPGIYMGRPTHSGGGGGGGGGGGGGGGGR_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
6        NaN  0.008571           NaN           NaN
7        NaN  0.012857           NaN           NaN
8        NaN  0.012857           NaN           NaN
11       NaN  0.010000           NaN           NaN
13       NaN  0.010000           NaN           NaN
14       NaN  0.007143           NaN           NaN
15       NaN  0.007143           NaN           NaN
16       NaN  0.007143           NaN           NaN
17       NaN  0.004286           NaN           NaN
19       NaN  0.011429           NaN           NaN
20  0.008571       NaN           NaN           NaN
21  0.010000       NaN           NaN           NaN
23  0.005714  0.071429           NaN           NaN
25  0.004286       NaN           NaN           NaN

PSM ID: psm_32, Peptide: _AHT(UniMod:21)PTPGIYMGRPTHSGGGGGGGGGGGGGGGGR_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
6   0.006667  0.006667           NaN           NaN
11       NaN  0.013333           NaN           NaN
13       NaN  0.006667           NaN           NaN
15       NaN  0.006667           NaN           NaN
16       NaN  0.006667           NaN           NaN
21  0.006667  0.023333           NaN           NaN
25  0.003333       NaN           NaN           NaN

PSM ID: psm_321, Peptide: _EEEEEIHS(UniMod:21)PTLLPEAQN_
        b_z2  y_z2  b_modloss_z2  y_modloss_z2
13  0.001298   NaN           NaN           NaN
16  0.002128   NaN           NaN           NaN

PSM ID: psm_322, Peptide: _EEEEEIHS(UniMod:21)PTLLPEAQN_
        b_z2  y_z2  b_modloss_z2  y_modloss_z2
15  0.004565   NaN           NaN           NaN

PSM ID: psm_323, Peptide: _EEEEEIHS(UniMod:21)PTLLPEAQN_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
10  0.004571       NaN           NaN           NaN
12  0.003962       NaN           NaN           NaN
13  0.001586       NaN           NaN           NaN
16       NaN  0.001739           NaN           NaN

PSM ID: psm_324, Peptide: _EEEEEIHS(UniMod:21)PTLLPEAQN_
        b_z2  y_z2  b_modloss_z2  y_modloss_z2
13  0.001434   NaN           NaN           NaN
14  0.008028   NaN           NaN           NaN
16  0.001275   NaN           NaN           NaN

PSM ID: psm_325, Peptide: _EEEEEIHS(UniMod:21)PTLLPEAQN_
        b_z2  y_z2  b_modloss_z2  y_modloss_z2
14  0.006362   NaN           NaN           NaN

PSM ID: psm_328, Peptide: _EEEEEIHS(UniMod:21)PTLLPEAQN_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
15   NaN  0.002888           NaN           NaN

PSM ID: psm_329, Peptide: _EEEEEIHS(UniMod:21)PTLLPEAQN_
    b_z2      y_z2  b_modloss_z2  y_modloss_z2
15   NaN  0.001945           NaN           NaN

PSM ID: psm_33, Peptide: _AHT(UniMod:21)PTPGIYMGRPTHSGGGGGGGGGGGGGGGGR_
     b_z2   y_z2  b_modloss_z2  y_modloss_z2
6     NaN  0.010           NaN           NaN
7     NaN  0.012           NaN           NaN
8     NaN  0.014           NaN           NaN
9     NaN  0.012           NaN           NaN
13    NaN  0.006           NaN           NaN
14    NaN  0.004           NaN           NaN
15    NaN  0.006           NaN           NaN
16    NaN  0.006           NaN           NaN
17    NaN  0.006           NaN           NaN
18  0.004    NaN           NaN           NaN
22  0.004    NaN           NaN           NaN
25  0.002    NaN           NaN           NaN
26  0.002    NaN           NaN           NaN

PSM ID: psm_34, Peptide: _AHT(UniMod:21)PTPGIYMGRPTHSGGGGGGGGGGGGGGGGR_
     b_z2   y_z2  b_modloss_z2  y_modloss_z2
6   0.005  0.005           NaN           NaN
13    NaN  0.010           NaN           NaN
18    NaN  0.020           NaN           NaN
19  0.005    NaN           NaN           NaN
23    NaN  0.050           NaN           NaN
27  0.001    NaN           NaN           NaN

PSM ID: psm_340, Peptide: _EGMNPSYDEYADS(UniMod:21)DEDQHDAYLER_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
9   0.057731       NaN           NaN           NaN
12       NaN  0.126117           NaN           NaN
17       NaN  0.029598           NaN           NaN

PSM ID: psm_341, Peptide: _EGMNPSYDEYADS(UniMod:21)DEDQHDAYLER_
        b_z2      y_z2  b_modloss_z2  y_modloss_z2
9   0.057731       NaN           NaN           NaN
12       NaN  0.126117           NaN           NaN
17       NaN  0.029598           NaN           NaN

PSM ID: psm_342, Peptide: _EGMNPSYDEYADS(UniMod:21)DEDQHDAYLER_
       b_z2  y_z2  b_modloss_z2  y_modloss_z2
9  0.016667   NaN           NaN           NaN

PSM ID: psm_343, Peptide: _EGMNPSYDEYADS(UniMod:21)DEDQHDAYLER_

In [51]:
# Tìm độ dài lớn nhất thực tế trong chuỗi AA sạch
clean_seqs = df['ModifiedPeptide'].str.replace(r'\(UniMod:\d+\)', '', regex=True).str.strip('_')
actual_max = clean_seqs.str.len().max() + 2 # +2 cho N và C term

print(f"Peptide dài nhất là: {actual_max}. Chốt max_len = {actual_max}")

# Khởi tạo dataset với con số thực tế đó

Peptide dài nhất là: 40. Chốt max_len = 40

In [30]:
df["target_col"].unique()

array(['y_z1', 'y_modloss_z1', 'b_z1', 'b_modloss_z1', 'y_z2', 'b_z2'],
      dtype=object)

In [31]:
df.head()

,PrecursorCharge,ModifiedPeptide,FragmentLossType,FragmentNumber,FragmentType,FragmentCharge,RelativeIntensity,psm_id,target_col,clean_seq,L,charge_num,loss_clean
0,2,_AEEDEILNRS(UniMod:21)PR_,noloss,1,y,1,0.085714,psm_0,y_z1,AEEDEILNRSPR,12,1,
1,2,_AEEDEILNRS(UniMod:21)PR_,noloss,2,y,1,1.000000,psm_0,y_z1,AEEDEILNRSPR,12,1,
2,2,_AEEDEILNRS(UniMod:21)PR_,noloss,3,y,1,0.028571,psm_0,y_z1,AEEDEILNRSPR,12,1,
3,2,_AEEDEILNRS(UniMod:21)PR_,noloss,4,y,1,0.014286,psm_0,y_z1,AEEDEILNRSPR,12,1,
4,2,_AEEDEILNRS(UniMod:21)PR_,noloss,5,y,1,0.057143,psm_0,y_z1,AEEDEILNRSPR,12,1,

In [33]:
import re
import pandas as pd

def parse_peptdeep_format(mod_peptide):
    # 1. Loại bỏ gạch dưới ở đầu/cuối
    peptide = mod_peptide.strip('_')
    
    # 2. Tìm tất cả các cụm (Modification) và vị trí của chúng
    # Dùng regex để tìm nội dung trong ngoặc đơn
    pattern = re.compile(r'([A-Z])(\([^)]+\))')
    
    clean_seq = re.sub(r'\([^)]+\)', '', peptide) # Chuỗi chỉ toàn Amino Acid
    nAA = len(clean_seq)
    
    mods = []
    mod_sites = []
    
    # Tìm các modification trên residue (A-Z)
    matches = list(re.finditer(r'([A-Z])(\([^)]+\))', peptide))
    
    # Tính toán vị trí thực tế trên chuỗi đã làm sạch
    current_clean_idx = 0
    temp_peptide = peptide
    
    # Cách đơn giản hơn để lấy site: 
    # Duyệt qua từng phần tách bởi regex
    parts = re.split(r'(\([^)]+\))', peptide)
    curr_site = 0
    for p in parts:
        if p.startswith('('):
            mods.append(p[1:-1]) # Bỏ dấu ngoặc
            mod_sites.append(curr_site) # Gán vào vị trí AA ngay trước đó
        else:
            curr_site += len(p)
            
    return clean_seq, ";".join(mods), ";".join([str(s) for s in mod_sites]), nAA

In [35]:
# Giả sử df_unique là bảng chứa các psm_id duy nhất
df_meta = df.drop_duplicates('psm_id').copy()

# Áp dụng hàm tách
parsed_data = df_meta['ModifiedPeptide'].apply(parse_peptdeep_format)
df_meta[['sequence', 'mods', 'mod_sites', 'nAA']] = pd.DataFrame(parsed_data.tolist(), index=df_meta.index)

# Bây giờ df_meta đã có đủ 4 cột: sequence, mods, mod_sites, nAA

In [36]:
df_meta.head()

,PrecursorCharge,ModifiedPeptide,FragmentLossType,FragmentNumber,FragmentType,FragmentCharge,RelativeIntensity,psm_id,target_col,clean_seq,L,charge_num,loss_clean,sequence,mods,mod_sites,nAA
0,2,_AEEDEILNRS(UniMod:21)PR_,noloss,1,y,1,0.085714,psm_0,y_z1,AEEDEILNRSPR,12,1,,AEEDEILNRSPR,UniMod:21,10,12
64,2,_AEEDEILNRS(UniMod:21)PR_,noloss,1,y,1,0.100000,psm_1,y_z1,AEEDEILNRSPR,12,1,,AEEDEILNRSPR,UniMod:21,10,12
128,2,_AEEDEILNRS(UniMod:21)PR_,noloss,1,y,1,0.083333,psm_2,y_z1,AEEDEILNRSPR,12,1,,AEEDEILNRSPR,UniMod:21,10,12
188,2,_AEEDEILNRS(UniMod:21)PR_,noloss,1,y,1,0.100000,psm_3,y_z1,AEEDEILNRSPR,12,1,,AEEDEILNRSPR,UniMod:21,10,12
249,2,_AEEDEILNRS(UniMod:21)PR_,noloss,1,y,1,0.087500,psm_4,y_z1,AEEDEILNRSPR,12,1,,AEEDEILNRSPR,UniMod:21,10,12

In [42]:
import sys
import os

sys.path.append(r'd:\DACN\tf-test\tf_modification_ms2')

In [45]:
df["ModifiedPeptide"].unique()

array(['_AEEDEILNRS(UniMod:21)PR_', '_AGDLLEDS(UniMod:21)PKRPK_',
       '_AGLGS(UniMod:21)PERPPK_',
       '_AHT(UniMod:21)PTPGIYMGRPTHSGGGGGGGGGGGGGGGGR_',
       '_AKS(UniMod:21)PQPPVEEEDEHFDDTVVC(UniMod:4)LDTYNC(UniMod:4)DLHFK_',
       '_ALASEKS(UniMod:21)PTADAKPAPK_', '_ALSAS(UniMod:21)HTDLAH_',
       '_ANGQENGHVKS(UniMod:21)NGDLSPK_',
       '_ANS(UniMod:21)PEKPPEAGAAHKPR_', '_ASAVSELS(UniMod:21)PR_',
       '_ASGQAFELILS(UniMod:21)PR_',
       '_(UniMod:1)AS(UniMod:21)GVAVSDGVIK_',
       '_(UniMod:1)AS(UniMod:21)GVQVADEVC(UniMod:4)R_',
       '_AS(UniMod:21)PAPGSGHPEGPGAHLDMNSLDR_',
       '_ATAPQTQHVS(UniMod:21)PMR_', '_ATNES(UniMod:21)EDEIPQLVPIGK_',
       '_ATS(UniMod:21)NVFAMFDQSQIQEFK_',
       '_AVTIANS(UniMod:21)PSKPSEKDSVVSLESQK_',
       '_AVT(UniMod:21)PVPTKTEEVSNLK_',
       '_C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVK_',
       '_C(UniMod:4)GSGPVHISGQHLVAVEEDAES(UniMod:21)EDEEEEDVKLLSISGK_',
       '_DELHIVEAEAMNYEGS(UniMod:21)PIKVTLATLK_',
       '_DGQDAIAQS(UniMod:21)PEKESK_',
       '_DKAPVQPQQS(UniMod:21)PAAAPGGTDEKPSGK_',
       '_DKS(UniMod:21)PVREPIDNLTPEER_',
       '_DSELY(UniMod:21)FLGT(UniMod:21)DT(UniMod:21)HKKK_',
       '_DTLRT(UniMod:21)PPRER_', '_DWEDDS(UniMod:21)DEDMSNFDR_',
       '_DYDEEEQGYDS(UniMod:21)EKEKK_', '_EEAS(UniMod:21)DDDMEGDEAVVR_',
       '_EEDEEPES(UniMod:21)PPEKK_',
       '_EEDEPEERS(UniMod:21)GDETPGSEVPGDK_',
       '_EEEEEIHS(UniMod:21)PTLLPEAQN_',
       '_EGEEPTVYS(UniMod:21)DEEEPKDESAR_',
       '_EGMNPSYDEYADS(UniMod:21)DEDQHDAYLER_',
       '_EKEIS(UniMod:21)DDEAEEEK_', '_EKEIS(UniMod:21)DDEAEEEKGEK_',
       '_ELSNS(UniMod:21)PLRENSFGS(UniMod:21)PLEFR_',
       '_ELYLS(UniMod:21)SS(UniMod:21)LKDLNKK_',
       '_ENVEYIEREES(UniMod:21)DGEYDEFGR_',
       '_ESEDKPEIEDVGS(UniMod:21)DEEEEKK_',
       '_ESSANNSVS(UniMod:21)PSESLR_', '_ETPHS(UniMod:21)PGVEDAPIAK_',
       '_ETSVSKEDT(UniMod:21)DHEEKASNEDVTK_',
       '_EVAT(UniMod:21)LC(UniMod:4)KLDILK_',
       '_EVEDKES(UniMod:21)EGEEEDEDEDLSK_', '_EVELVS(UniMod:21)E_',
       '_FAS(UniMod:21)DDEHDEHDENGATGPVK_',
       '_FAS(UniMod:21)DDEHDEHDENGATGPVKR_',
       '_FEEESKEPVADEEEEDS(UniMod:21)DDDVEPITEFR_'], dtype=object)

In [43]:



from model.featurize import get_batch_aa_indices, get_batch_mod_feature, parse_instrument_indices


aa_indices = get_batch_aa_indices(df_meta['sequence'].values)

# 2. Lấy Modification Features (Ma trận hóa học 109 chiều)
# Kết quả: (Batch_size, nAA + 2, 109)
mod_x = get_batch_mod_feature(df_meta)

# 3. Lấy Instrument Indices
# Kết quả: List các con số (0, 1, 2...)
instrument_indices = parse_instrument_indices(["QE"] * len(df_meta))

ModuleNotFoundError: No module named 'alphabase.modification'